repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-meripseq_logo_light.png
    - docs/images/nf-core-meripseq_logo_light.png
    - docs/images/nf-core-meripseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-meripseq_logo_light.png
    - docs/images/nf-core-meripseq_logo_light.png
    - docs/images/nf-core-meripseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: nf
  name: meripseq
  description: 'Data analysis pipeline for MeRIPseq '
  author: Yujia Qin
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: false
